"""High-level RAG chatbot exposed to the API layer."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from src.rag.agent.openrouter_llm import OpenRouterLLM
from src.rag.agent.prompts import SYSTEM_PROMPT, build_user_prompt
from src.rag.config import Settings, get_settings
from src.rag.databases.qdrant_client import RetrievedChunk
from src.rag.retrieval import Retriever
from src.rag.utils import get_logger

logger = get_logger(__name__)


@dataclass
class ChatResponse:
    """Result returned by the chatbot to its caller.

    Attributes
    ----------
    answer : str
        Final answer generated by the LLM.
    citations : List[dict]
        Lightweight serialisable representation of every chunk that was sent
        to the LLM. Each citation contains the chunk index used in the
        answer, the source link, the title, and the similarity score.
    model : str
        The model identifier that generated this response.
    """

    answer: str
    citations: List[Dict[str, Any]] = field(default_factory=list)
    model: str = ""


class FinanceRAGChatbot:
    """Vietnamese finance RAG chatbot.

    The chatbot is a thin orchestrator on top of :class:`Retriever` and
    :class:`OpenRouterLLM`. It is intentionally stateless; conversation memory
    can be layered on later by stacking turns in the user prompt.

    Parameters
    ----------
    retriever : Retriever
        Semantic retriever backed by Qdrant.
    llm : OpenRouterLLM
        OpenRouter chat LLM with multi-model support.
    settings : Optional[Settings]
        Settings override.
    """

    def __init__(
        self,
        retriever: Retriever,
        llm: OpenRouterLLM,
        settings: Optional[Settings] = None,
    ) -> None:
        self._retriever = retriever
        self._llm = llm
        self._settings = settings or get_settings()

    def ask(
        self,
        question: str,
        model: Optional[str] = None,
        top_k: Optional[int] = None,
        score_threshold: Optional[float] = None,
        filters: Optional[Dict[str, Any]] = None,
    ) -> ChatResponse:
        """Answer a user question with RAG over the CafeF corpus.

        Parameters
        ----------
        question : str
            User question (Vietnamese or English).
        model : Optional[str]
            OpenRouter model ID to use. When ``None``, falls back to
            ``settings.openrouter.default_model``. Must be in the allowed
            models list; see :meth:`OpenRouterLLM.available_models`.
        top_k : Optional[int]
            Override the default ``top_k`` retrieval setting.
        score_threshold : Optional[float]
            Override the default score threshold.
        filters : Optional[dict]
            Equality filters on stored metadata
            (e.g. ``{"ticker_symbol": "ACB"}``).

        Returns
        -------
        ChatResponse
            Generated answer + citations + model used.
        """
        retrieval = self._retriever.retrieve(
            query=question,
            top_k=top_k,
            score_threshold=score_threshold,
            filters=filters,
        )
        context = retrieval.to_context()
        user_prompt = build_user_prompt(question=question, context=context)
        answer = self._llm.generate(
            system_prompt=SYSTEM_PROMPT,
            user_prompt=user_prompt,
            model=model,
        )
        resolved_model = model or self._settings.openrouter.default_model

        return ChatResponse(
            answer=answer.strip(),
            citations=self._deduplicate_citations(retrieval.chunks),
            model=resolved_model,
        )

    @staticmethod
    def _deduplicate_citations(chunks: List[RetrievedChunk]) -> List[Dict[str, Any]]:
        """Build citation list with unique articles only.

        When multiple chunks belong to the same article, only the
        highest-scoring chunk is kept. This prevents the frontend from
        displaying duplicate source cards.

        Parameters
        ----------
        chunks : List[RetrievedChunk]
            Ranked chunks from retrieval.

        Returns
        -------
        List[Dict[str, Any]]
            De-duplicated citation entries, re-indexed starting from 1.
        """
        seen: Dict[str, Dict[str, Any]] = {}
        for chunk in chunks:
            link = chunk.article_link
            if link in seen:
                # Keep the entry with the higher score
                if chunk.score > seen[link]["score"]:
                    seen[link] = FinanceRAGChatbot._citation_of(0, chunk)
            else:
                seen[link] = FinanceRAGChatbot._citation_of(0, chunk)
        # Re-index citations sequentially
        citations = []
        for idx, entry in enumerate(seen.values(), start=1):
            entry["index"] = idx
            citations.append(entry)
        return citations

    @staticmethod
    def _citation_of(idx: int, chunk: RetrievedChunk) -> Dict[str, Any]:
        """Render a single chunk into a serialisable citation entry."""
        return {
            "index": idx,
            "score": round(chunk.score, 4),
            "article_link": chunk.article_link,
            "title": chunk.metadata.get("title"),
            "post_date": chunk.metadata.get("post_date"),
            "ticker_symbol": chunk.metadata.get("ticker_symbol"),
        }

