-- =====================================================================
-- Financial News RAG Stack - Database Schema Initialization
-- =====================================================================
-- 
-- This script creates the base schema for the metadata storage database.
-- Tables for storing article metadata, embeddings, and processing status.
--
-- Execution: Automatically run during container initialization
-- Prerequisites: PostgreSQL 17 with PostGIS extension (optional)
--
-- =====================================================================

-- Set session properties
SET client_encoding = 'UTF8';
SET timezone = 'UTC';

-- =====================================================================
-- Create Schema
-- =====================================================================

-- Create main schema for RAG application
CREATE SCHEMA IF NOT EXISTS rag_metadata;

-- Grant permissions
GRANT ALL PRIVILEGES ON SCHEMA rag_metadata TO :POSTGRES_USER;

-- Set search path
ALTER DATABASE :POSTGRES_DB SET search_path TO rag_metadata, public;


-- =====================================================================
-- Articles Table
-- =====================================================================
-- Stores metadata about financial news articles

CREATE TABLE IF NOT EXISTS rag_metadata.articles (
    article_id BIGSERIAL PRIMARY KEY,
    
    -- Article identification
    external_id VARCHAR(255) UNIQUE NOT NULL,  -- ID from source (CAFEF, etc.)
    source_name VARCHAR(100) NOT NULL,         -- Source website name
    source_url VARCHAR(1000) NOT NULL,         -- Article URL
    
    -- Article content
    title VARCHAR(500) NOT NULL,               -- Article title
    content TEXT NOT NULL,                     -- Full article text
    summary TEXT,                              -- Generated or provided summary
    
    -- Article metadata
    published_date TIMESTAMP NOT NULL,         -- Publication date
    scraped_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Processing status
    processing_status VARCHAR(50) DEFAULT 'new'::text CHECK (
        processing_status IN ('new', 'processing', 'completed', 'failed', 'archived')
    ),
    
    -- Article classification
    category VARCHAR(100),                     -- News category/section
    tags TEXT[],                               -- Array of tags
    
    -- Quality metrics
    is_valid BOOLEAN DEFAULT true,             -- Data quality flag
    validation_errors TEXT,                    -- Errors found during validation
    
    -- Additional metadata
    metadata JSONB,                            -- Flexible additional data
    
    -- Audit fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for articles table
CREATE INDEX idx_articles_source_id ON rag_metadata.articles(source_name, external_id);
CREATE INDEX idx_articles_published_date ON rag_metadata.articles(published_date DESC);
CREATE INDEX idx_articles_status ON rag_metadata.articles(processing_status);
CREATE INDEX idx_articles_created_at ON rag_metadata.articles(created_at DESC);
CREATE INDEX idx_articles_title ON rag_metadata.articles USING GIN(to_tsvector('english', title));
CREATE INDEX idx_articles_content ON rag_metadata.articles USING GIN(to_tsvector('english', content));


-- =====================================================================
-- Embeddings Table
-- =====================================================================
-- Stores vector embeddings for articles (generated by embedding models)

CREATE TABLE IF NOT EXISTS rag_metadata.embeddings (
    embedding_id BIGSERIAL PRIMARY KEY,
    
    -- Reference to article
    article_id BIGINT NOT NULL REFERENCES rag_metadata.articles(article_id) ON DELETE CASCADE,
    
    -- Embedding identification
    embedding_type VARCHAR(100) NOT NULL,     -- Type: 'title', 'content', 'summary'
    model_name VARCHAR(255) NOT NULL,         -- Model used (e.g., 'sentence-transformers/all-MiniLM-L6-v2')
    model_version VARCHAR(50),                -- Model version
    
    -- Embedding vector
    embedding_vector FLOAT8[] NOT NULL,       -- Vector array (float32 encoded as float64)
    embedding_dimension INT NOT NULL,         -- Dimension of embedding vector
    
    -- Metadata
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Quality metrics
    confidence_score FLOAT,                   -- Confidence in embedding quality
    
    CONSTRAINT unique_article_embedding_type UNIQUE (article_id, embedding_type, model_name)
);

-- Create indexes for embeddings table
CREATE INDEX idx_embeddings_article_id ON rag_metadata.embeddings(article_id);
CREATE INDEX idx_embeddings_type ON rag_metadata.embeddings(embedding_type);
CREATE INDEX idx_embeddings_model ON rag_metadata.embeddings(model_name);


-- =====================================================================
-- Named Entity Recognition (NER) Labels
-- =====================================================================
-- Stores NER labels and annotations for articles

CREATE TABLE IF NOT EXISTS rag_metadata.ner_labels (
    ner_id BIGSERIAL PRIMARY KEY,
    
    -- Reference to article
    article_id BIGINT NOT NULL REFERENCES rag_metadata.articles(article_id) ON DELETE CASCADE,
    
    -- Entity information
    entity_text VARCHAR(500) NOT NULL,        -- The entity text
    entity_type VARCHAR(100) NOT NULL,        -- Entity type: PERSON, ORG, LOC, MONEY, DATE, etc.
    entity_confidence FLOAT,                  -- Model confidence score (0-1)
    
    -- Position in text
    start_pos INT NOT NULL,                   -- Character position start
    end_pos INT NOT NULL,                     -- Character position end
    
    -- Labeling information
    labeled_by VARCHAR(100),                  -- Model name or human annotator
    labeling_method VARCHAR(50),              -- 'automated' or 'manual'
    
    -- Validation
    is_validated BOOLEAN DEFAULT false,       -- Whether validated by human
    validation_notes TEXT,                    -- Validation comments
    
    -- Audit fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for NER labels table
CREATE INDEX idx_ner_labels_article_id ON rag_metadata.ner_labels(article_id);
CREATE INDEX idx_ner_labels_type ON rag_metadata.ner_labels(entity_type);
CREATE INDEX idx_ner_labels_entity ON rag_metadata.ner_labels(entity_text);
CREATE INDEX idx_ner_labels_created ON rag_metadata.ner_labels(created_at DESC);


-- =====================================================================
-- Extraction Spans (Relation Extraction)
-- =====================================================================
-- Stores text spans and relationships extracted from articles

CREATE TABLE IF NOT EXISTS rag_metadata.extraction_spans (
    span_id BIGSERIAL PRIMARY KEY,
    
    -- Reference to article
    article_id BIGINT NOT NULL REFERENCES rag_metadata.articles(article_id) ON DELETE CASCADE,
    
    -- Span information
    span_text VARCHAR(1000) NOT NULL,         -- The extracted span
    span_type VARCHAR(100) NOT NULL,          -- Type: 'event', 'relationship', 'statement', etc.
    span_confidence FLOAT,                    -- Model confidence (0-1)
    
    -- Position in text
    start_pos INT NOT NULL,
    end_pos INT NOT NULL,
    
    -- Related entities
    subject_entity VARCHAR(500),              -- Subject in relation
    predicate VARCHAR(500),                   -- Relationship type
    object_entity VARCHAR(500),               -- Object in relation
    
    -- Extraction information
    extracted_by VARCHAR(100),                -- Model/method name
    extraction_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Validation
    is_validated BOOLEAN DEFAULT false,
    validation_notes TEXT,
    
    CONSTRAINT valid_span_positions CHECK (start_pos < end_pos)
);

-- Create indexes for extraction spans table
CREATE INDEX idx_extraction_spans_article ON rag_metadata.extraction_spans(article_id);
CREATE INDEX idx_extraction_spans_type ON rag_metadata.extraction_spans(span_type);
CREATE INDEX idx_extraction_spans_subject ON rag_metadata.extraction_spans(subject_entity);
CREATE INDEX idx_extraction_spans_object ON rag_metadata.extraction_spans(object_entity);


-- =====================================================================
-- Processing Events Log
-- =====================================================================
-- Tracks all processing events and status changes

CREATE TABLE IF NOT EXISTS rag_metadata.processing_events (
    event_id BIGSERIAL PRIMARY KEY,
    
    -- Reference to article
    article_id BIGINT NOT NULL REFERENCES rag_metadata.articles(article_id) ON DELETE CASCADE,
    
    -- Event information
    event_type VARCHAR(100) NOT NULL,         -- Type: 'scrape', 'validate', 'embed', 'extract', 'index', 'archive'
    event_status VARCHAR(50) NOT NULL,        -- Status: 'started', 'completed', 'failed', 'skipped'
    
    -- Process details
    processor_name VARCHAR(255),               -- Service/worker that processed
    processor_version VARCHAR(50),             -- Processor version
    
    -- Results
    result_message TEXT,                      -- Success or error message
    result_metadata JSONB,                    -- Additional result data (timing, counts, etc.)
    
    -- Performance metrics
    processing_time_ms INT,                   -- Time taken in milliseconds
    items_processed INT,                      -- Number of items processed
    items_failed INT,                         -- Number of items failed
    
    -- Timestamps
    event_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for processing events table
CREATE INDEX idx_processing_events_article ON rag_metadata.processing_events(article_id);
CREATE INDEX idx_processing_events_type ON rag_metadata.processing_events(event_type);
CREATE INDEX idx_processing_events_status ON rag_metadata.processing_events(event_status);
CREATE INDEX idx_processing_events_timestamp ON rag_metadata.processing_events(event_timestamp DESC);


-- =====================================================================
-- Dataset Metadata
-- =====================================================================
-- Tracks datasets and their composition for RAG evaluation

CREATE TABLE IF NOT EXISTS rag_metadata.datasets (
    dataset_id BIGSERIAL PRIMARY KEY,
    
    -- Dataset information
    dataset_name VARCHAR(255) NOT NULL UNIQUE,
    dataset_type VARCHAR(100) NOT NULL,      -- Type: 'training', 'validation', 'test', 'eval'
    description TEXT,
    
    -- Dataset statistics
    total_articles INT DEFAULT 0,
    created_articles INT DEFAULT 0,
    labeled_articles INT DEFAULT 0,
    annotated_articles INT DEFAULT 0,
    
    -- Versioning
    version VARCHAR(50) NOT NULL DEFAULT '1.0',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Metadata
    metadata JSONB                            -- Additional dataset metadata
);

-- Create indexes for datasets table
CREATE INDEX idx_datasets_type ON rag_metadata.datasets(dataset_type);
CREATE INDEX idx_datasets_created ON rag_metadata.datasets(created_at DESC);


-- =====================================================================
-- Dataset Membership
-- =====================================================================
-- Links articles to datasets

CREATE TABLE IF NOT EXISTS rag_metadata.dataset_members (
    member_id BIGSERIAL PRIMARY KEY,
    
    -- References
    dataset_id BIGINT NOT NULL REFERENCES rag_metadata.datasets(dataset_id) ON DELETE CASCADE,
    article_id BIGINT NOT NULL REFERENCES rag_metadata.articles(article_id) ON DELETE CASCADE,
    
    -- Membership info
    added_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Split information
    split_type VARCHAR(50),                   -- 'train', 'val', 'test'
    
    CONSTRAINT unique_dataset_article UNIQUE (dataset_id, article_id)
);

-- Create indexes for dataset members table
CREATE INDEX idx_dataset_members_dataset ON rag_metadata.dataset_members(dataset_id);
CREATE INDEX idx_dataset_members_article ON rag_metadata.dataset_members(article_id);


-- =====================================================================
-- User Activity Log
-- =====================================================================
-- Tracks user interactions with the system

CREATE TABLE IF NOT EXISTS rag_metadata.user_activity (
    activity_id BIGSERIAL PRIMARY KEY,
    
    -- User information
    user_id VARCHAR(255) NOT NULL,
    activity_type VARCHAR(100) NOT NULL,     -- Type: 'view', 'edit', 'label', 'export', etc.
    
    -- Resource information
    resource_type VARCHAR(100),               -- Type: 'article', 'label', 'dataset', etc.
    resource_id BIGINT,                       -- ID of the resource
    
    -- Activity details
    action_details TEXT,
    
    -- Timestamps
    activity_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for user activity table
CREATE INDEX idx_user_activity_user ON rag_metadata.user_activity(user_id);
CREATE INDEX idx_user_activity_type ON rag_metadata.user_activity(activity_type);
CREATE INDEX idx_user_activity_timestamp ON rag_metadata.user_activity(activity_timestamp DESC);


-- =====================================================================
-- Create Update Triggers
-- =====================================================================
-- Automatically update the updated_at timestamp

CREATE OR REPLACE FUNCTION rag_metadata.update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for tables with updated_at
CREATE TRIGGER articles_update_timestamp
BEFORE UPDATE ON rag_metadata.articles
FOR EACH ROW
EXECUTE FUNCTION rag_metadata.update_timestamp();

CREATE TRIGGER ner_labels_update_timestamp
BEFORE UPDATE ON rag_metadata.ner_labels
FOR EACH ROW
EXECUTE FUNCTION rag_metadata.update_timestamp();

CREATE TRIGGER datasets_update_timestamp
BEFORE UPDATE ON rag_metadata.datasets
FOR EACH ROW
EXECUTE FUNCTION rag_metadata.update_timestamp();


-- =====================================================================
-- Grant Permissions
-- =====================================================================

GRANT ALL PRIVILEGES ON SCHEMA rag_metadata TO :POSTGRES_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA rag_metadata TO :POSTGRES_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA rag_metadata TO :POSTGRES_USER;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA rag_metadata TO :POSTGRES_USER;

-- Create read-only role for applications
CREATE ROLE rag_readonly WITH LOGIN PASSWORD :'POSTGRES_PASSWORD';
GRANT CONNECT ON DATABASE :POSTGRES_DB TO rag_readonly;
GRANT USAGE ON SCHEMA rag_metadata TO rag_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA rag_metadata TO rag_readonly;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA rag_metadata GRANT SELECT ON TABLES TO rag_readonly;


-- =====================================================================
-- Database Initialization Complete
-- =====================================================================

-- Print summary
\echo '=========================================='
\echo 'RAG Metadata Database Initialization'
\echo '=========================================='
\echo 'Schema: rag_metadata'
\echo 'Tables created:'
\echo '  - articles'
\echo '  - embeddings'
\echo '  - ner_labels'
\echo '  - extraction_spans'
\echo '  - processing_events'
\echo '  - datasets'
\echo '  - dataset_members'
\echo '  - user_activity'
\echo '=========================================='
